# Generated by Django 4.0.6 on 2024-08-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
