# Generated by Django 5.0.8 on 2024-08-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketinfo_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
