# Generated by Django 5.0.8 on 2024-08-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_chatmessage_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
